@local=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBkNmU2YjIyYjU2NjM1MzNmZmFjMzIiLCJiaXoiOmZhbHNlLCJpc0FkbWluIjp0cnVlLCJlbWFpbCI6Inlvc3NpQGdtYWlsLmNvbSIsImlhdCI6MTY5NTM5NDUyMH0.Rb9uURfnXE6lfg6WJxPPvz3i2J8SR_yHESv_FR94nkQ

////////////////////////////User API//////////////////////////////////////////////
### Create New User
POST {{local}}/users
Content-Type: application/json

{
    "name":{
      "first": "gal",
      "last" : "tomer"
    },
    "phone": "052486485",
    "email": "yossi@gmail.com",
    "password": "!QAZ2wsx",
    "biz": "true",
    "isAdmin": "true",
    "bizNumber": "18"
}

### Authenticate (login)
POST {{local}}/users/login
Content-Type: application/json

{
  "email": "yossi@gmail.com",
  "password": "!QAZ2wsx"
}

### get all users
GET {{local}}/users
x-auth-token: {{token}}

### get user by id
GET {{local}}/users/650d78145a726dd18a83ab86
x-auth-token: {{token}}


### Update user by id
PUT {{local}}/users/650d6e6b22b5663533ffac32
x-auth-token: {{token}}
Content-Type: application/json

{
  "phone": "0504484265",
  "email": "yossi@gmail.com",
  "password": "!QAZ2wsx",
  "bizNumber": "19"
}

### Toggle Biz user by id
PATCH  {{local}}/users/650d6e6b225663533ffac32
x-auth-token: {{token}}

### Delete user by id
DELETE {{local}}/users/650d71a9906c92f024a5ba2d
x-auth-token: {{token}}
////////////////////////////User API//////////////////////////////////////////////


////////////////////////////Card API//////////////////////////////////////////////
### Get all Cards
GET {{local}}/cards

### Get my Cards
GET {{local}}/cards/my-cards
x-auth-token: {{token}}

### Get card by ID
GET {{local}}/cards/650d982610645d2a5df12180


### Create New Card
POST {{local}}/cards
Content-Type: application/json
x-auth-token: {{token}}

{
  "title": "ofir",
  "subtitle": "matan",
  "description": "web deveoloper",
  "phone": "0505875037",
  "email": "hadar@gmail.com",
  "address": {
    "country": "IL",
    "city": "Rehovot",
    "street": "Max Shein",
    "houseNumber": "23",
    "zip": "17"
  }
}

### Delete Card
DELETE   {{local}}/cards/650d982610645d2a5df12193
Content-Type: application/json
x-auth-token: {{token}}

### Like Card
PATCH  {{local}}/cards/650d982610645d2a5df12160
Content-Type: application/json
x-auth-token: {{token}}

### Update Card
PUT {{local}}/cards/650d97a617f29d069391b57c
Content-Type: application/json
x-auth-token: {{token}}

{
  "title": "gal",
  "subtitle": "hayne2",
  "description": "full stack development",
  "phone": "0505875037",
  "email": "galhayne@gmail.com",
  "address": {
    "country": "IL",
    "city": "Rehovot",
    "street": "Max Shein",
    "houseNumber": "23",
    "zip": "5"
  }
}

////////////////////////////Card API//////////////////////////////////////////////


































