@local=http://localhost:3000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTBkNzgxNDVhNzI2ZGQxOGE4M2FiODYiLCJiaXoiOmZhbHNlLCJpc0FkbWluIjpmYWxzZSwiZW1haWwiOiJnYWwzQGdtYWlsLmNvbSIsImlhdCI6MTY5NTM4Mjc5M30.9YbxJ66NpfKQjUILyYd4d391D-jZSbyEVI4EjrVm7BA

////////////////////////////User API//////////////////////////////////////////////
### Create New User
POST {{local}}/users
Content-Type: application/json

{
    "name":{
      "first": "gal",
      "last" : "tomer"
    },
    "phone": "052486485",
    "email": "gal33@gmail.com",
    "password": "!QAZ2wsx",
    "biz": "true",
    "isAdmin": "true",
    "bizNumber": "18"
}

### Authenticate (login)
POST {{local}}/users/login
Content-Type: application/json

{
  "email": "gal3@gmail.com",
  "password": "!QAZ2ws"
}

### get all users
GET {{local}}/users
x-auth-token: {{token}}

### get user by id
GET {{local}}/users/650d78145a726dd18a83ab86
x-auth-token: {{token}}


### Update user by id
PUT {{local}}/users/650d6e6b22b5663533ffac32
x-auth-token: {{token}}
Content-Type: application/json

{
  "phone": "0504484265",
  "email": "yossi@gmail.com",
  "password": "!QAZ2wsx",
  "bizNumber": "19"
}

### Toggle Biz user by id
PATCH  {{local}}/users/650d6cfd3e6663842dcdc
x-auth-token: {{token}}

### Delete user by id
DELETE {{local}}/users/650d71a9906c92f024a5ba2d
x-auth-token: {{token}}
////////////////////////////User API//////////////////////////////////////////////


////////////////////////////Card API//////////////////////////////////////////////
### Get all Cards
GET {{local}}/cards

### Get my Cards
GET {{local}}/cards/my-cards
x-auth-token: {{token}}

{
  "user_id": "650c290a04cffe923649844f"
}

### Get card by ID
GET {{local}}/cards/650c24169b2fa95ffd267216


### Create New Card
POST {{local}}/cards
Content-Type: application/json
x-auth-token: {{token}}

{
  "title": "tomer",
  "subtitle": "hayne",
  "description": "web deveoloper",
  "phone": "0505875037",
  "email": "hadar@gmail.com",
  "address": {
    "country": "IL",
    "city": "Rehovot",
    "street": "Max Shein",
    "houseNumber": "23",
    "zip": "5"
  }
}

### Delete Card
DELETE   {{local}}/cards/650c3a480bfcac7c1e7d3a70
Content-Type: application/json
x-auth-token: {{token}}

### Like Card
PATCH  {{local}}/cards/650c184d12c8c2859fbefe67
Content-Type: application/json
x-auth-token: {{token}}

### Update Card
PUT {{local}}/cards/650c4eb5fa4ea191acdd0fd1
Content-Type: application/json
x-auth-token: {{token}}

{
  "title": "gal",
  "subtitle": "hayne",
  "description": "full stack development",
  "phone": "0505875037",
  "email": "gal@gmail.com",
  "address": {
    "country": "IL",
    "city": "Rehovot",
    "street": "Max Shein",
    "houseNumber": "23",
    "zip": "5"
  }
}

////////////////////////////Card API//////////////////////////////////////////////


































